/* wolfhsm_client_glue.c
 *
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfTrust.
 *
 * wolfTrust is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfTrust is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

/*
 * Guest-side wolfHSM client glue.
 *
 * Provides:
 *  - A custom whTransportClientCb that routes Send/Recv through NSC veneers
 *    into the secure CMSE monitor (mirroring cmse_transport.c on the server
 *    side).
 *  - wolfhsm_guest_init(): initialises the wolfHSM client context and
 *    registers wh_Client_CryptoCb as the wolfCrypt crypto-callback device
 *    so that wc_* calls are forwarded to the secure-side HSM.
 *  - wolftrust_guest_rng_stub(): the CUSTOM_RAND_GENERATE_BLOCK hook required
 *    by user_settings.h. Once the client is ready this delegates entropy
 *    requests to the secure-side HSM.
 *
 * Buffer layout per guest (WT_HSM_BUF_SIZE = 512 bytes):
 *   +0x000   8 B   request  CSR  (whTransportMemCsr)
 *   +0x008 248 B   request  data (written by guest)
 *   +0x100   8 B   response CSR  (whTransportMemCsr)
 *   +0x108 248 B   response data (written by secure monitor)
 *
 * Both slots start at the linker-provided _hsm_transport_base and
 * (_hsm_transport_base + WT_HSM_BUF_SIZE/2) respectively; the data area of each slot immediately
 * follows its 8-byte CSR at (csr + 1).
 */

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#include "memory_map.h"

#include "wolfhsm/wh_settings.h"
#include "wolfhsm/wh_error.h"
#include "wolfhsm/wh_comm.h"
#include "wolfhsm/wh_transport_mem.h"
#include "wolfhsm/wh_client.h"
#include "wolfhsm/wh_client_crypto.h"
#include "wolfhsm/wh_client_cryptocb.h"

#include "wolfssl/wolfcrypt/cryptocb.h"

/* ---------------------------------------------------------------------------
 * Per-guest buffer base.
 *
 * The object is compiled once and linked into both guests, so this must not
 * depend on a compile-time guest ID.  The linker script places
 * _hsm_transport_base inside each guest's own RAM image.
 * ---------------------------------------------------------------------------*/
extern uint32_t _hsm_transport_base;

/* ---------------------------------------------------------------------------
 * NSC veneer declarations.
 *
 * Resolved at guest link time via the secure image's CMSE import library
 * ($(BUILD_DIR)/secure_cmse_implib.o, generated by ld --out-implib during
 * the secure link). Each symbol carries the fixed address of its veneer
 * in .gnu.sgstubs; the linker patches the BL targets accordingly.
 *
 * Following the wolfBoot pattern: secure side owns the addresses, guest
 * imports symbol names only — no brittle address constants in this file.
 *
 * The BL into an NSC region is a normal Thumb branch; the M33's
 * security extension transparently performs the SG transition when the
 * fetched instruction is in an NSC SAU region. cmse_nonsecure_call
 * function-pointer attribute is only required when CALLING THROUGH a
 * pointer typed for that purpose — direct external calls don't need it.
 * ---------------------------------------------------------------------------*/
extern int  WolfTrust_HSM_Submit(uint16_t size);
extern int  WolfTrust_HSM_Poll  (uint16_t seq);
extern int  WolfTrust_HSM_Cancel(uint16_t seq);

/* ---------------------------------------------------------------------------
 * Transport context
 * ---------------------------------------------------------------------------*/
typedef struct wt_guest_transport_ctx {
    whTransportMemCsr   *req_csr;
    whTransportMemCsr   *resp_csr;
    uint64_t             last_resp_notify;
    whCommSetConnectedCb connectcb;
    void                *connectcb_arg;
} wt_guest_transport_ctx_t;

static wt_guest_transport_ctx_t g_guest_tx;

/* ---------------------------------------------------------------------------
 * Transport callbacks
 * ---------------------------------------------------------------------------*/

static int guest_tx_init(void *ctx_v, const void *cfg_v,
                         whCommSetConnectedCb connectcb, void *connectcb_arg)
{
    wt_guest_transport_ctx_t *ctx = (wt_guest_transport_ctx_t *)ctx_v;

    (void)cfg_v;

    if (ctx == NULL) {
        return WH_ERROR_BADARGS;
    }

    ctx->req_csr  = (whTransportMemCsr *)(uintptr_t)&_hsm_transport_base;
    ctx->resp_csr = (whTransportMemCsr *)(uintptr_t)
                    ((uintptr_t)&_hsm_transport_base + WT_HSM_BUF_SIZE / 2u);

    /* Baseline: whatever is already in the response CSR.  Reading the whole
     * 8-byte union avoids a partial read that could race with the monitor. */
    ctx->last_resp_notify = ctx->resp_csr->u64;

    ctx->connectcb     = connectcb;
    ctx->connectcb_arg = connectcb_arg;

    if (connectcb != NULL) {
        connectcb(connectcb_arg, WH_COMM_CONNECTED);
    }

    return WH_ERROR_OK;
}

static int guest_tx_cleanup(void *ctx_v)
{
    wt_guest_transport_ctx_t *ctx = (wt_guest_transport_ctx_t *)ctx_v;

    if (ctx == NULL) {
        return WH_ERROR_BADARGS;
    }

    if (ctx->connectcb != NULL) {
        ctx->connectcb(ctx->connectcb_arg, WH_COMM_DISCONNECTED);
    }

    ctx->req_csr  = NULL;
    ctx->resp_csr = NULL;

    return WH_ERROR_OK;
}

/* Send a request to the secure monitor.
 *
 * Protocol:
 *  1. Copy data into the request slot's data area (immediately after the CSR).
 *  2. Write the payload length into req_csr->s.len.
 *  3. Issue a DSB to ensure the payload is visible before the notify signal.
 *  4. Increment req_csr->s.notify to signal a new request.
 *  5. Call WolfTrust_HSM_Submit() to hand the request to the monitor. */
static int guest_tx_send(void *ctx_v, uint16_t data_size, const void *data)
{
    wt_guest_transport_ctx_t *ctx = (wt_guest_transport_ctx_t *)ctx_v;

    if (ctx == NULL || data == NULL || ctx->req_csr == NULL) {
        return WH_ERROR_BADARGS;
    }
    if (data_size > WOLFHSM_CFG_COMM_DATA_LEN) {
        return WH_ERROR_BADARGS;
    }

    /* Write payload into the data area that follows the request CSR header. */
    memcpy((uint8_t *)(ctx->req_csr + 1), data, data_size);

    /* Commit the length, then barrier, then increment the notify counter.
     * Order matters: the monitor reads notify first, then len, then data. */
    ctx->req_csr->s.len = data_size;
    __asm volatile("dsb sy" ::: "memory");
    ctx->req_csr->s.notify++;

    /* Cross the CMSE boundary. The monitor marks this guest waiting and runs
     * the secure HSM tasklet from the CMSE service path. */
    return WolfTrust_HSM_Submit(data_size);
}

/* Receive a response from the secure monitor.
 *
 * Protocol:
 *  1. Call WolfTrust_HSM_Poll() to query monitor-visible response state.
 *  2. Compare the full 8-byte response CSR against last_resp_notify.
 *  3. On change, validate the length and copy the data out.
 *  4. Update last_resp_notify so the next call does not re-deliver. */
static int guest_tx_recv(void *ctx_v, uint16_t *out_size, void *data)
{
    wt_guest_transport_ctx_t *ctx = (wt_guest_transport_ctx_t *)ctx_v;
    uint64_t cur;
    uint16_t sz;

    if (ctx == NULL || out_size == NULL || data == NULL ||
        ctx->resp_csr == NULL) {
        return WH_ERROR_BADARGS;
    }

    /* Query the monitor before checking for a response. */
    (void)WolfTrust_HSM_Poll(0);

    /* Read the full 8-byte CSR atomically as a single 64-bit load. */
    cur = ctx->resp_csr->u64;
    if (cur == ctx->last_resp_notify) {
        return WH_ERROR_NOTREADY;
    }

    sz = ctx->resp_csr->s.len;
    if (sz > WOLFHSM_CFG_COMM_DATA_LEN) {
        /* Response is malformed; advance baseline so we do not loop. */
        ctx->last_resp_notify = cur;
        return WH_ERROR_ABORTED;
    }

    /* Copy the response payload from the area following the response CSR. */
    memcpy(data, (const uint8_t *)(ctx->resp_csr + 1), sz);
    *out_size             = sz;
    ctx->last_resp_notify = cur;

    return WH_ERROR_OK;
}

static const whTransportClientCb g_guest_transport_cb = {
    .Init    = guest_tx_init,
    .Send    = guest_tx_send,
    .Recv    = guest_tx_recv,
    .Cleanup = guest_tx_cleanup,
};

/* ---------------------------------------------------------------------------
 * wolfHSM client context and configuration (module-level singletons)
 * ---------------------------------------------------------------------------*/
static whClientContext    g_client_ctx;
static whClientConfig     g_client_cfg;
static whCommClientConfig g_comm_cfg;
static int                g_client_ready;

/* ---------------------------------------------------------------------------
 * Public API
 * ---------------------------------------------------------------------------*/

/* Initialise the wolfHSM client and register the crypto-callback device.
 *
 * Call this once from Reset_Handler (or equivalent early-init code) after
 * .data/.bss are ready.  wc_* calls will be routed to the secure HSM once
 * this returns WH_ERROR_OK. */
int wolfhsm_guest_init(void)
{
    int rc;

    g_client_ready = 0;

    g_comm_cfg.transport_cb      = &g_guest_transport_cb;
    g_comm_cfg.transport_context = &g_guest_tx;
    g_comm_cfg.transport_config  = NULL;
    g_comm_cfg.client_id         = 0u; /* secure side assigns the real id */

    g_client_cfg.comm = &g_comm_cfg;

    rc = wh_Client_Init(&g_client_ctx, &g_client_cfg);
    if (rc != WH_ERROR_OK) {
        return rc;
    }

    rc = wc_CryptoCb_RegisterDevice(WH_DEV_ID, wh_Client_CryptoCb,
                                    &g_client_ctx);
    if (rc != 0) {
        return rc;
    }

    g_client_ready = 1;

    return WH_ERROR_OK;
}

/* Return a pointer to the initialised client context for callers that need
 * direct access to wolfHSM client API functions. */
whClientContext *wolfhsm_guest_client(void)
{
    return &g_client_ctx;
}

/* ---------------------------------------------------------------------------
 * RNG stub — CUSTOM_RAND_GENERATE_BLOCK hook
 *
 * user_settings.h maps CUSTOM_RAND_GENERATE_BLOCK to this function.  Some
 * wolfCrypt paths still call the entropy hook directly even when the crypto-cb
 * device is selected, so delegate to the same secure-side wolfHSM client after
 * wolfhsm_guest_init() has completed.  Before init, fail closed.
 * ---------------------------------------------------------------------------*/
int wolftrust_guest_rng_stub(unsigned char *output, unsigned int sz)
{
    if (output == NULL && sz != 0u) {
        return WH_ERROR_BADARGS;
    }
    if (g_client_ready == 0) {
        return -1;
    }

    return wh_Client_RngGenerate(&g_client_ctx, output, sz);
}

/* ---------------------------------------------------------------------------
 * wc_GenerateSeed — wolfCrypt OS seed hook
 *
 * wolfCrypt's random.c compiles PollAndReSeed() regardless of
 * CUSTOM_RAND_GENERATE_BLOCK; that function references wc_GenerateSeed to
 * reseed the DRBG.  In normal HSM-delegated operation the code path is never
 * reached, but the linker requires the symbol.  Delegate to the same HSM-backed
 * hook used by CUSTOM_RAND_GENERATE_BLOCK.
 *
 * Signature matches wolfSSL's wolfssl/wolfcrypt/random.h: OS_Seed is a
 * typedef struct, byte is uint8_t, word32 is uint32_t.
 * ---------------------------------------------------------------------------*/
#include "wolfssl/wolfcrypt/random.h"

int wc_GenerateSeed(OS_Seed *os, byte *output, word32 sz)
{
    (void)os;
    return wolftrust_guest_rng_stub((unsigned char *)output, (unsigned int)sz);
}

/* ---------------------------------------------------------------------------
 * Minimal bump-pointer heap for wolfCrypt memory.c
 *
 * wolfCrypt's memory.c calls malloc/free/realloc for internal buffers (e.g.
 * DRBG state, ECC key scratch).  The guest has no C library heap; we provide
 * a trivial bump allocator backed by a static pool.  free() and realloc() are
 * stubs sufficient for the crypto-cb delegation path where actual computation
 * stays in the secure world and the guest only formats request messages.
 *
 * Pool size: 3 KiB covers the cryptocb-delegation path (DRBG state, small
 * key formatting buffers). Larger values starve the NS stack — 8 KiB used
 * up half of the guest's 16 KiB RAM and crashed the wolfCrypt benchmark
 * with a wild-PC fault from stack overflow.
 * ---------------------------------------------------------------------------*/
#define WT_HEAP_POOL_SZ (3u * 1024u)

static uint8_t  s_heap_pool[WT_HEAP_POOL_SZ];
static uint32_t s_heap_offset = 0u;

void *malloc(size_t size)
{
    uint32_t aligned;

    if (size == 0u) {
        return NULL;
    }
    /* Round up to 8-byte alignment for all targets. */
    aligned = (uint32_t)((size + 7u) & ~7u);
    if (s_heap_offset + aligned > WT_HEAP_POOL_SZ) {
        return NULL; /* OOM — increase WT_HEAP_POOL_SZ */
    }
    void *ptr = (void *)&s_heap_pool[s_heap_offset];
    s_heap_offset += aligned;
    return ptr;
}

void free(void *ptr)
{
    /* Bump allocator: no individual free.  Acceptable because crypto-cb
     * delegation path creates and destroys keys within single operations. */
    (void)ptr;
}

void *realloc(void *ptr, size_t size)
{
    /* Simple fallback: allocate a fresh block and copy from old.
     * Safe for wolfCrypt usage patterns where realloc is rare. */
    void *new_ptr;
    if (size == 0u) {
        free(ptr);
        return NULL;
    }
    new_ptr = malloc(size);
    if (new_ptr != NULL && ptr != NULL) {
        memcpy(new_ptr, ptr, size); /* may copy more than originally alloc'd */
    }
    return new_ptr;
}
